schema_version = "1.0.0"

id = "shatter"
version = "1.1.6"
name = "Shatter OSS"
tagline = "Shatter allows easily creating and exporting Smash Hit segments"
maintainer = "Knot126 <cddepppp256@gmail.com>"
type = "add-on"
website = "https://codeberg.org/knot126/Shatter-OSS/wiki"
tags = ["Import-Export", "Scene", "User Interface"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:MIT",
  "SPDX:Zlib",
]

# Optional: required by some licenses.
copyright = [
  "2020-2024 Knot126",
  "2023-2024 Yorshex",
]

# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
[permissions]
network = "Run the Quick Test server"
files = "Various read and write operations with segments"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "__pycache__/",
] 
