schema_version = "1.0.0"

id = "shatter"
version = "1.6.3"
name = "Shatter OSS"
tagline = "Create, export, and test Smash Hit segments"
maintainer = "Knot126 <cddepppp256@gmail.com>"
type = "add-on"
website = "https://codeberg.org/knot126/Shatter-OSS/wiki"
tags = ["Import-Export", "Scene", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:MIT",
  "SPDX:Zlib",
]

copyright = [
  "2020-2025 Knot126",
  "2023-2025 Maxim \"yorshex\" Ershov",
]

platforms = ["windows-arm64", "windows-x64", "linux-x64"]

[permissions]
network = "Run the Quick Test server"
files = "Various read and write operations with segments"

[build]
paths_exclude_pattern = [
  "__pycache__/",
] 
